# Generated by Django 4.2.6 on 2023-10-12 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(choices=[(0, 'B-Tech Artificial Intelliegnence'), (1, 'BE Computer Science and Engineering')], default=0, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.CharField(choices=[(0, 'Head of the Department'), (1, 'Assistant Head of the Department'), (3, 'Lecturer')], default=0, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(choices=[('001', 'B-Tech Artificial Intelliegnence and Machine Learninig'), ('243', 'B-Tech Artificial Intelliegnence and Data Science')], default='001', max_length=50, null=True)),
                ('semester', models.PositiveIntegerField(choices=[(1, 'SEM - 1'), (2, 'SEM - 2')], default=1, null=True)),
                ('year', models.PositiveIntegerField(choices=[(1, 'I'), (2, 'II')], default=1, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('parent_mobile', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Advisor', to='core.staff')),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='HOD', to='core.staff')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Mentor', to='core.staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='advisor_for',
            field=models.ManyToManyField(related_name='astudents', to='core.student'),
        ),
        migrations.AddField(
            model_name='staff',
            name='mentor_for',
            field=models.ManyToManyField(related_name='menties', to='core.student'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
