# Generated by Django 4.2.6 on 2023-10-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.PositiveIntegerField(choices=[(0, 'B-Tech Artificial Intelliegnence'), (1, 'BE Computer Science and Engineering')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.PositiveIntegerField(choices=[(0, 'Head of the Department'), (1, 'Assistant Head of the Department'), (3, 'Lecturer')], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.PositiveIntegerField(choices=[(1, 'SEM - 1'), (2, 'SEM - 2'), (3, 'SEM - 3'), (4, 'SEM - 4'), (5, 'SEM - 5'), (6, 'SEM - 6'), (7, 'SEM - 7'), (8, 'SEM - 8')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.PositiveIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=1, null=True),
        ),
    ]
