# Generated by Django 4.2.6 on 2023-10-12 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_staff_department_alter_staff_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='advisor_for',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='mentor_for',
        ),
    ]
