# Generated by Django 4.2.6 on 2023-10-12 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_staff_advisor_for_remove_staff_mentor_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='OD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=150)),
                ('subject', models.TextField()),
                ('start', models.DateTimeField(verbose_name='From-Date')),
                ('end', models.DateTimeField(verbose_name='To-Date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_advisor', to='core.staff')),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_hod', to='core.staff')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_mentor', to='core.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_student', to='core.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LEAVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=150)),
                ('subject', models.TextField()),
                ('start', models.DateTimeField(verbose_name='From-Date')),
                ('end', models.DateTimeField(verbose_name='To-Date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_advisor', to='core.staff')),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_hod', to='core.staff')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_mentor', to='core.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_student', to='core.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
