# Generated by Django 4.2.6 on 2023-10-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_od_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='od',
            old_name='student',
            new_name='user',
        ),
    ]
