# Generated by Django 4.2.6 on 2023-10-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_student_od_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='od',
            old_name='status',
            new_name='Astatus',
        ),
        migrations.AddField(
            model_name='od',
            name='Hstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='od',
            name='Mstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
