# Generated by Django 4.2.6 on 2023-10-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_od_certificate_od_proof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LEAVE',
        ),
    ]
