# Generated by Django 4.2.6 on 2023-10-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_leave_certificate_alter_leave_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='GATEPASS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=150)),
                ('start', models.DateTimeField(verbose_name='From-Date')),
                ('end', models.DateTimeField(verbose_name='To-Date')),
                ('proof', models.FileField(blank=True, upload_to='od/proof')),
                ('certificate', models.FileField(blank=True, upload_to='od/proof/certificate')),
                ('Astatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('Mstatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('Hstatus', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sg_student', to='core.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
