# Generated by Django 4.2.6 on 2023-10-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_gatepass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='gatepass',
            name='proof',
        ),
    ]
