# Generated by Django 4.2.6 on 2023-10-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_hod_alter_staffrating_comments_ratingquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrating',
            name='ques',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ratingquestions'),
        ),
    ]
