# Generated by Django 4.2.6 on 2023-10-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_staffrating_ques'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingquestions',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='staffrating',
            name='is_feedbacked',
            field=models.BooleanField(default=False),
        ),
    ]
