# Generated by Django 4.2.6 on 2023-10-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_ratingquestions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='feedback_for',
            field=models.ManyToManyField(related_name='for_staff_rating', to='core.staffrating'),
        ),
    ]
