# Generated by Django 4.2.6 on 2023-10-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_student_feedback_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrating',
            name='is_feedbacked',
        ),
        migrations.CreateModel(
            name='IndividualStaffRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_feedbacked', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ratings', models.ManyToManyField(related_name='StaffRating_Individual', to='core.staffrating')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
