# Generated by Django 4.2.6 on 2023-10-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_staffrating_is_feedbacked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='feedback_for',
            field=models.ManyToManyField(related_name='for_staff_rating', to='core.individualstaffrating'),
        ),
    ]
