# Generated by Django 4.2.6 on 2023-10-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_staff_my_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='staffs',
            field=models.ManyToManyField(related_name='my_staffs', to='core.staff'),
        ),
    ]
