# Generated by Django 4.2.6 on 2023-10-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_hod_staffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='assign_feedback',
            field=models.ManyToManyField(related_name='assign_feed', to='core.staff'),
        ),
    ]
