# Generated by Django 4.2.6 on 2023-10-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_hod_assign_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='students',
            field=models.ManyToManyField(related_name='students', to='core.student'),
        ),
    ]
