# Generated by Django 4.2.6 on 2023-10-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_hod_assign_feedback_alter_hod_staffs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='feedback_history',
            field=models.ManyToManyField(blank=True, related_name='for_staff_rating_history', to='core.individualstaffrating'),
        ),
    ]
