# Generated by Django 4.2.6 on 2023-11-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_student_section_alter_hod_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='department',
            field=models.PositiveIntegerField(choices=[(0, 'B-Tech Artificial Intelliegnence'), (1, 'BE Computer Science and Engineering'), (3, 'BE Electrical and Communication Engineering'), (2, 'None')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.PositiveIntegerField(choices=[(0, 'B-Tech Artificial Intelliegnence'), (1, 'BE Computer Science and Engineering'), (3, 'BE Electrical and Communication Engineering'), (2, 'None')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.PositiveIntegerField(choices=[(0, 'Artificial Intelliegnence and Machine Learninig'), (1, 'Artificial Intelliegnence and Data Science'), (2, 'A'), (3, 'B'), (4, 'C')], default=2),
        ),
        migrations.CreateModel(
            name='SpotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=1, null=True)),
                ('section', models.PositiveIntegerField(choices=[(0, 'Artificial Intelliegnence and Machine Learninig'), (1, 'Artificial Intelliegnence and Data Science'), (2, 'A'), (3, 'B'), (4, 'C')], default=2)),
                ('feebacks', models.ManyToManyField(blank=True, to='core.individualstaffrating')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_spot', to='core.staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_spot', to='core.staff')),
            ],
        ),
    ]
