# Generated by Django 4.2.6 on 2023-11-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_hod_department_alter_staff_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotfeedback',
            name='students',
            field=models.ManyToManyField(blank=True, to='core.student'),
        ),
    ]
