# Generated by Django 4.2.6 on 2023-11-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_spotfeedback_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='get_spot_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
