# Generated by Django 4.2.6 on 2023-11-01 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_hod_get_spot_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotfeedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
