# Generated by Django 4.2.6 on 2023-11-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_spotfeedback_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotfeedback',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
