# Generated by Django 4.2.6 on 2023-11-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_spotfeedback_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='hod',
            name='spot_feedback',
            field=models.ManyToManyField(blank=True, to='core.spotfeedback'),
        ),
    ]
