# Generated by Django 4.2.6 on 2023-11-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_spotfeedback_sompleted_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotfeedback',
            old_name='sompleted_students',
            new_name='completed_students',
        ),
    ]
