# Generated by Django 4.2.6 on 2023-11-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rename_sompleted_students_spotfeedback_completed_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotfeedback',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='Spot/qrcodes/'),
        ),
        migrations.AddField(
            model_name='spotfeedback',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
